config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'users#index'

  resources :users

  resources :spells

end

app/models/spell.rb
class Spell < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  before_action :set_spell, only: [:show, :edit, :update, :destroy]

  def index
    @spells = Spell.all
  end

  def show
  end

  def new
    @spell = Spell.new
  end

  def edit
  end

  def create
    @spell = Spell.new(spell_params)

    respond_to do |format|
      if @spell.save
        format.html { redirect_to @spell, notice: 'spell was successfully created.' }
        format.json { render :show, status: :created, location: @spell }
      else
        format.html { render :new }
        format.json { render json: @spell.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @spell.update(spell_params)
        format.html { redirect_to @spell, notice: 'spell was successfully updated.' }
        format.json { render :show, status: :ok, location: @spell }
      else
        format.html { render :edit }
        format.json { render json: @spell.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @spell.destroy
    respond_to do |format|
      format.html { redirect_to spells_url, notice: 'Spell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_spell
      @spell = Spell.find(params[:id])
    end

    def spell_params
      params.require(:spell).permit(:name, :level, :spell_type, :casting_time, :range, :duration, :info)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, :authenticate_user!, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spells</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spells/_form.html.erb
<%= form_for(@spell) do |f| %>
  <% if @spell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spell.errors.count, "error") %> prohibited this spell from being saved:</h2>

      <ul>
      <% @spell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </p>

  <p>
    <%= f.label :spell_type %><br>
    <%= f.text_field :spell_type %>
  </p>

  <p>
    <%= f.label :casting_time %><br>
    <%= f.text_field :casting_time %>
  </p>

  <p>
    <%= f.label :range %><br>
    <%= f.text_field :range %>
  </p>

  <p>
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </p>

  <p>
    <%= f.label :info %><br>
    <%= f.text_area :info %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spells/edit.html.erb
<h1>Editing Spell</h1>

<%= render 'form' %>

<%= link_to 'Show', @spell %> |
<%= link_to 'Back', spells_path %>

app/views/spells/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spells</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Type</th>
      <th>Casting Time</th>
      <th>Range</th>
      <th>Duration</th>
      <th>Info</th>
    </tr>
  </thead>

  <tbody>
    <% @spells.each do |spell| %>
      <tr>
        <td><%= spell.name %></td>
        <td><%= spell.level %></td>
        <td><%= spell.spell_type %></td>
        <td><%= spell.casting_time %></td>
        <td><%= spell.range %></td>
        <td><%= spell.duration %></td>
        <td><%= spell.info %></td>
        <td><%= link_to 'Show', spell %></td>
        <td><%= link_to 'Edit', edit_spell_path(spell) %></td>
        <td><%= link_to 'Destroy', spell, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spell', new_spell_path %>

app/views/spells/new.html.erb
<h1>New Spell</h1>

<%= render 'form' %>

<%= link_to 'Back', spells_path %>

app/views/spells/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Type</th>
      <th>Casting Time</th>
      <th>Time</th>
      <th>Duration</th>
      <th>Info</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @spell.name %></td>
      <td><%= @spell.level %></td>
      <td><%= @spell.spell_type %></td>
      <td><%= @spell.casting_time %></td>
      <td><%= @spell.range %></td>
      <td><%= @spell.duration %></td>
      <td><%= @spell.info %></td>
      <td><%= link_to 'Edit', edit_spell_path(@spell) %></td>
      <td><%= link_to 'Back', spells_path %></td>
    </tr>
  </tbody>
</table>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_area :last_name %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email address</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email address</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @user.first_name %></td>
      <td><%= @user.last_name %></td>
      <td><%= @user.email %></td>
      <td><%= link_to 'Edit', edit_user_path(@user) %></td>
      <td><%= link_to 'Back', users_path %></td>
    </tr>
  </tbody>
</table>